# Generated by Django 5.0.3 on 2024-04-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('취미', '취미'), ('음식', '음식'), ('프로그래밍', '프로그래밍')], max_length=20),
        ),
    ]
