# Generated by Django 5.0.4 on 2024-04-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
    ]
