# Generated by Django 5.0.4 on 2024-04-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
