# Generated by Django 5.0.4 on 2024-04-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0005_alter_post_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
    ]
