# Generated by Django 5.0.3 on 2024-04-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
